chore: initialize docker in server
ancora-imparo/notes pull request #35
Opened 2021-08-11 18:05 UTC by kartikp36

2021-08-12 16:43 UTC, harsilspatel requested changes
Good start, can do better

2021-08-12 16:43 UTC, harsilspatel commented on server/.dockerignore
> +**/.dockerignore
Find a better way to do this, instead of ignore a billion folders, just include the ones you want

2021-08-12 16:43 UTC, harsilspatel commented on server/Dockerfile
> +COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
We don't use npm-shrinkwrap.json

2021-08-16 20:00 UTC, kartikp36 commented
This is ready to be merged now @harsilspatel

2021-08-20 17:04 UTC, merged